### ISSUE TITLE
Where is this text from?

### ISSUE THREAD

**Issue by razeedazee** [AndrewSav/Remnant2SaveAnalyzer#1]
I can't seem to work out where it's from.

![image](https://github.com/AndrewSav/Remnant2SaveAnalyzer/assets/141931230/d0ca1c98-dfa2-4316-8c77-6220f6f786eb)

**Comment by AndrewSav** [comment]
It's from [here](https://github.com/AndrewSav/lib.remnant2.analyzer/blob/8801762226f75fb2b3677ab0d428e11cd547df19/db.json#L2309)

I'm actually editing the database in a google spreadsheet and then exporting it to json, let me fix these

**Comment by AndrewSav** [comment]
I fixed it [here](https://github.com/AndrewSav/lib.remnant2.analyzer/commit/a13ad34dfaeb8c5c7e139183a669cbe22529cb81) but it will need a nuget package push and, more importantly the main program release. I will do this when I finish the next bunch of changes I'm working on right now.

**Comment by razeedazee** [comment]
Thanks and i know where to look if i see more now.

**Comment by AndrewSav** [comment]
The typos is fixed in `0.0.4`
