### ISSUE TITLE
0.0.5 closes when clicking world analyser

### ISSUE THREAD

**Issue by razeedazee** [AndrewSav/Remnant2SaveAnalyzer#13]
I updated from 0.0.4 to 0.0.5 and immediately it closes.

I also tried fresh download of the release, it just shows this, but no errors.

![image](https://github.com/AndrewSav/Remnant2SaveAnalyzer/assets/141931230/3fc00459-d8c8-411c-95fc-affdc404e4e9)

**Comment by AndrewSav** [comment]
I pushed 0.0.6, let me know if it works

**Comment by AndrewSav** [comment]
Also pushed 0.0.7 to resolve some issues with Save Backups
