### ISSUE TITLE
Show coop items filter is broken

### ISSUE THREAD

**Issue by Cosmitz** [AndrewSav/Remnant2SaveAnalyzer#23]
With the 'show coop items' off, not only does it still show coop items, it also doesn't recognize missing items as missing. I was wondering what was happening since it showed i had all the items, up until i got a new World drop and i looked at the app confused. It was listing it as there, but not as missing.

**Comment by AndrewSav** [comment]
@Cosmitz thanks, I'll have a look, I actually never used the options personally, so not surprised that it might be broken

**Comment by AndrewSav** [comment]
Should work now, let me know if it's not quite right
