### ISSUE TITLE
Error Upon Starting Program: 'System.String' actual type: 'null'

### ISSUE THREAD

**Issue by tangentThought** [AndrewSav/Remnant2SaveAnalyzer#27]
I have been using Save Guardian and saw that this fork might be better. However, in the first time trying to use the program and am met with the error below immediately and nothing shows up when trying to use the World Analyzer tab.

System.InvalidOperationException: requested value is of a different type. Requested type: 'System.String' actual type: 'null'
   at lib.remnant2.saves.Model.Properties.Property.Get[T]()
   at lib.remnant2.analyzer.Analyzer.Analyze(String folderPath, Dataset oldDataset)
   at Remnant2SaveAnalyzer.RemnantSave.UpdateCharacters() in Remnant2SaveAnalyzer\RemnantSave.cs:line 106

**Comment by tangentThought** [comment]
[latest save folder.zip](https://github.com/user-attachments/files/15811249/latest.save.folder.zip)

Attached a copy of my save.

**Comment by AndrewSav** [comment]
Thank you for your report! I have fixed this crash in 0.0.20!

**Comment by tangentThought** [comment]
It works perfectly! And I can say that this fork is way better to use. Thank you for fixing!
