### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by ishwar44** [AndrewSav/Remnant2SaveAnalyzer#33]
When using the world analyzer I get a 
System.NullReferenceException: Object reference not set to an instance of an object.
at lib.remnant2.analyzer.Analyzer.Analyze(String folderPath, Dataset oldDataset)
at Remnant2SaveAnalyzer.RemnantSave.UpdateCharacters() in Remnant2SaveAnalyzer\RemnantSave.cs:line 106

**Comment by AndrewSav** [comment]
@ishwar44  Upload your saves please.

**Comment by ishwar44** [comment]
[remnant2_saves.zip](https://github.com/user-attachments/files/17983308/remnant2_saves.zip)
had this exception occur on all saves

**Comment by AndrewSav** [comment]
@ishwar44 it looks like these are older saves. Can you update the game to the lastest version, go to the game, and touch the stone with each character and try again. If you still have the exception, please attach the saves after you touched the stone with every character in the latest game version.

**Comment by ishwar44** [comment]
The game is on the latest version when I made these saves but I can try again.

**Comment by AndrewSav** [comment]
> The game is on the latest version. But I can try again

The save files that you sent are not from the latest game version. The latest game version is 453438. In order for the game to update all the save files you need to start the game, load each character and touch stone with the character and close the game. After that the saves will be updated.

**Comment by ishwar44** [comment]
oh okay, I only use the 2nd character really and I have not used the other 3 in a while but I thought only 1 needed to be on the latest save. It seems to work now that all characters are on the latest

**Comment by AndrewSav** [comment]
Nice, thank you for checking back!
