### ISSUE TITLE
Item images

### ISSUE THREAD

**Issue by AndrewSav** [AndrewSav/Remnant2SaveAnalyzer#4]
It should be relatively easy to get images for most items from the wiki

**Comment by joshpayette** [comment]
Depending on what size images you want, I can give you a dump from the S3 bucket I use in the Remnant 2 Toolkit, or probably go back and find most of the high-res versions to save you some trouble on it.

**Comment by AndrewSav** [comment]
@joshpayette thank you, much appreciated! Currently @crackedmind is working on the UI re-write with [WPF UI 3.0](https://github.com/lepoco/wpfui), once we get that off the ground than I will revisit this one and will get back to you for more info.

**Comment by AndrewSav** [comment]
Closing in favour  of https://github.com/AndrewSav/Remnant2SaveAnalyzer/issues/28
